**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/grouping-and-sorting).**

---

# Introduction

In these exercises we'll apply groupwise analysis to our dataset.

Run the code cell below to load the data before running the exercises.

In [1]:
import pandas as pd

reviews = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
#pd.set_option("display.max_rows", 5)

from learntools.core import binder; binder.bind(globals())
from learntools.pandas.grouping_and_sorting import *
print("Setup complete.")

Setup complete.

In [20]:
point_group = reviews.groupby('points')
point_group.count()

,country,description,designation,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
points,,,,,,,,,,,,
80,397,397,250,395,397,328,136,275,271,397,397,397
81,692,692,406,680,692,584,293,433,423,692,692,692
82,1835,1836,1087,1772,1835,1556,907,1054,1012,1836,1836,1836
83,3024,3025,1844,2886,3024,2503,1142,2112,2021,3025,3025,3025
84,6478,6480,3943,6099,6478,5320,2375,4395,4196,6480,6480,6480
85,9529,9530,5980,8902,9529,7722,3308,7133,6729,9530,9530,9530
86,12595,12600,8246,11745,12595,10361,4467,9580,9006,12600,12600,12600
87,16927,16933,11286,15767,16927,14293,6102,12871,12065,16933,16933,16933
88,17198,17207,11831,16014,17198,14503,6538,14356,13626,17207,17206,17207
89,12208,12226,8920,11324,12208,9998,4095,10660,10056,12226,12226,12226
90,15403,15410,11412,14361,15403,12747,6349,12946,12291,15410,15410,15410
91,11353,11359,8858,10564,11353,9583,5006,9765,9442,11359,11359,11359
92,9606,9613,7887,8871,9606,8185,4279,7833,7612,9613,9613,9613
93,6489,6489,5457,5935,6489,5611,2854,5408,5239,6489,6489,6489
94,3758,3758,3166,3449,3758,3317,1696,3018,2924,3758,3758,3758
95,1535,1535,1249,1406,1535,1332,623,1221,1190,1535,1535,1535
96,523,523,419,482,523,458,216,405,396,523,523,523
97,229,229,170,207,229,203,77,166,164,229,229,229
98,77,77,53,69,77,72,32,61,60,77,77,77
99,33,33,29,28,33,31,12,21,21,33,33,33
100,19,19,13,19,19,17,4,14,14,19,19,19

# Exercises

In [24]:
# reviews['taster_twitter_handle'].value_counts()
reviews_written = reviews.groupby('taster_twitter_handle').count()
reviews_written

,country,description,designation,points,price,province,region_1,region_2,taster_name,title,variety,winery
taster_twitter_handle,,,,,,,,,,,,
@AnneInVino,3676,3685,3130,3685,3398,3676,1395,0,3685,3685,3685,3685
@JoeCz,5145,5147,3428,5147,5012,5145,3406,101,5147,5147,5147,5147
@bkfiona,27,27,17,27,27,27,18,0,27,27,27,27
@gordone_cellars,4177,4177,2660,4177,4171,4177,4171,3087,4177,4177,4177,4177
@kerinokeefe,10776,10776,7549,10776,9874,10776,10749,0,10776,10776,10776,10776
@laurbuzz,1832,1835,1268,1835,1713,1832,618,18,1835,1835,1835,1835
@mattkettmann,6332,6332,4568,6332,6237,6332,6331,6284,6332,6332,6332,6332
@paulgwine,9531,9532,6482,9532,9498,9531,9487,8923,9532,9532,9532,9532
@suskostrzewa,1080,1085,682,1085,1073,1080,243,159,1085,1085,1085,1085
@vboone,9537,9537,6764,9537,9507,9537,9532,9022,9537,9537,9537,9537
@vossroger,25512,25514,17963,25514,20172,25512,18635,2,25514,25514,25514,25514
@wawinereport,4966,4966,3550,4966,4925,4966,4791,4743,4966,4966,4966,4966
@wineschach,15127,15134,12275,15134,14951,15127,10477,69,15134,15134,15134,15134
@winewchristina,6,6,2,6,6,6,6,5,6,6,6,6
@worldwineguys,971,1005,780,1005,995,971,0,0,1005,1005,1005,1005

## 1.
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [25]:
# Your code here
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()

reviews_written
# Check your answer
q1.check()

Correct:


```python
reviews_written = reviews.groupby('taster_twitter_handle').size()
```
or
```python
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
```

In [15]:
q1.hint()
#q1.solution()

Hint: Use the `groupby` operation and `size()` (or `count()`).

## 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [40]:
price_group = reviews.groupby('price')
series2 = price_group.points.max()
series2

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [41]:
best_rating_per_price = series2

# Check your answer
q2.check()

Correct

In [26]:
q2.hint()
#q2.solution()

Hint: Use `max()` and `sort_index()`.  The relevant columns in the DataFrame are `price` and `points`.

## 3.
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [44]:
vareity_group = reviews.groupby('variety')

my_dict = {
    'min':vareity_group.price.min(),
    'max':vareity_group.price.max()
}

df = pd.DataFrame(my_dict)

In [46]:
df

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

In [47]:
price_extremes = df
# Check your answer
q3.check()

Correct

In [ ]:
#q3.hint()
#q3.solution()

## 4.
What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [53]:
df.sort_values(['min', 'max'], ascending = [False, False])

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

In [54]:
#both min and max were to be sorted in descending values
sorted_varieties =  df.sort_values(['min', 'max'], ascending = [False, False])

# Check your answer
q4.check()

Correct

In [48]:
q4.hint()
#q4.solution()

Hint: Use `sort_values()`, and provide a list of names to sort by.

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [58]:
reviews.groupby('taster_name').points.mean()

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [59]:
reviewer_mean_ratings = reviews.groupby('taster_name').points.mean()

# Check your answer
q5.check()

Correct

In [55]:
q5.hint()
#q5.solution()

Hint: Use `mean()`.

Are there significant differences in the average scores assigned by the various reviewers? Run the cell below to use the `describe()` method to see a summary of the range of values.

In [60]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

## 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [63]:
 reviews.groupby(['country', 'variety']).size().

country    variety
Argentina  Barbera                         1
           Bonarda                       105
           Bordeaux-style Red Blend       89
           Bordeaux-style White Blend      1
           Cabernet Blend                  8
                                        ...
Uruguay    Tannat-Cabernet Franc           2
           Tannat-Merlot                   6
           Tannat-Syrah                    1
           Tempranillo-Tannat              1
           White Blend                     1
Length: 1612, dtype: int64

In [ ]:
country_variety_counts = ____

# Check your answer
q6.check()

In [62]:
q6.hint()
q6.solution()

Hint: Use `groupby()`, and provide a list of columns to group by.  You may also find `size()` and `sort_values()` to be useful!

Solution:
```python
country_variety_counts = reviews.groupby(['country', 'variety']).size().sort_values(ascending=False)
```

# Keep going

Move on to the [**data types and missing data**](https://www.kaggle.com/residentmario/data-types-and-missing-values).

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*