# Updating rows and columns and modifying Data

In [1]:
import pandas as pd

In [3]:
people = {
    'first_name':['Corey','Jane','John'],
    'last_name':['Schafer','Doe','Doe'],
    'email':['CoreySchafer@gmail.com','janeDoe@gmail.com','JohnDoe@gmail.com']
}

In [4]:
people_df = pd.DataFrame(people)

In [5]:
people_df

  first_name last_name                   email
0      Corey   Schafer  CoreySchafer@gmail.com
1       Jane       Doe       janeDoe@gmail.com
2       John       Doe       JohnDoe@gmail.com

In [6]:
people_df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

# Updating Columns

In [7]:
people_df.columns = ['first','last','email']

In [8]:
people_df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       janeDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [9]:
#uppercasing all of the columns names
people_df.columns = [x.upper() for x in people_df.columns]

In [10]:
people_df

   FIRST     LAST                   EMAIL
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       janeDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [11]:
people_df.columns = ['first_name','last_name','email']

In [12]:
people_df

  first_name last_name                   email
0      Corey   Schafer  CoreySchafer@gmail.com
1       Jane       Doe       janeDoe@gmail.com
2       John       Doe       JohnDoe@gmail.com

In [13]:
#method to replace characters with each other
people_df.columns = people_df.columns.str.replace('_',' ')

In [14]:
people_df

  first name last name                   email
0      Corey   Schafer  CoreySchafer@gmail.com
1       Jane       Doe       janeDoe@gmail.com
2       John       Doe       JohnDoe@gmail.com

In [15]:
people_df.columns = people_df.columns.str.replace(' ','_')

In [16]:
people_df

  first_name last_name                   email
0      Corey   Schafer  CoreySchafer@gmail.com
1       Jane       Doe       janeDoe@gmail.com
2       John       Doe       JohnDoe@gmail.com

In [17]:
#modifying specific columns instead of all the columns
people_df.rename(columns={'first_name':'first','last_name':'last'}, inplace = True)

In [18]:
people_df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       janeDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [19]:
#modifying specific data in our rows
people_df.loc[2] = ['John','Smith','JohnSmith@gmail.com']

In [20]:
people_df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       janeDoe@gmail.com
2   John    Smith     JohnSmith@gmail.com

In [21]:
#changing a single columns when there are many
people_df.loc[2,['last','email']] = ['Doe','JohnDoe@gmail.com']

In [22]:
people_df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       janeDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [23]:
#changing single values
people_df.loc[2,'last'] = 'Gupta'

In [24]:
people_df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       janeDoe@gmail.com
2   John    Gupta       JohnDoe@gmail.com

In [25]:
filt = (people_df['email'] == 'JohnDoe@gmail.com')
people_df[filt]['last']

2    Gupta
Name: last, dtype: object

In [33]:
#updating values of multiple rows
people_df['email'] = people_df['email'].str.lower()

In [34]:
people_df

   first     last                   email
0  Corey  Schafer  coreyschafer@gmail.com
1   Jane      Doe       janedoe@gmail.com
2   John    Smith       johndoe@gmail.com

In [35]:
# 4methods
# apply
# map
# applymap
# replace

#apply applies a function to a series or a dataframe
people_df['email'].apply(len)

0    22
1    17
2    17
Name: email, dtype: int64

In [36]:
def update_email(email):
  return email.upper()

people_df['email'].apply(update_email)

0    COREYSCHAFER@GMAIL.COM
1         JANEDOE@GMAIL.COM
2         JOHNDOE@GMAIL.COM
Name: email, dtype: object

In [38]:
people_df['email'] = people_df['email'].apply(update_email)

In [39]:
people_df

   first     last                   email
0  Corey  Schafer  COREYSCHAFER@GMAIL.COM
1   Jane      Doe       JANEDOE@GMAIL.COM
2   John    Smith       JOHNDOE@GMAIL.COM

In [40]:
people_df['email'] = people_df['email'].apply(lambda x: x.lower())

In [41]:
people_df

   first     last                   email
0  Corey  Schafer  coreyschafer@gmail.com
1   Jane      Doe       janedoe@gmail.com
2   John    Smith       johndoe@gmail.com

In [42]:
#apply working on dataFrames
# runs a function on each row or column of that data frame

people_df.apply(len) #default is rows

first    3
last     3
email    3
dtype: int64

In [44]:
people_df.apply(len, axis = 'columns')

0    3
1    3
2    3
dtype: int64

In [45]:
#using apply to grab the minimum value from our series 

people_df.apply(pd.Series.min)  #checks for each column

first                     Corey
last                        Doe
email    coreyschafer@gmail.com
dtype: object

In [47]:
people_df.apply(lambda x: x.min()) # x is a series return the minimun of that series

first                     Corey
last                        Doe
email    coreyschafer@gmail.com
dtype: object

In [49]:
#apply map is used to apply a function to every individual value in a data frame
# only works on data frames

people_df.applymap(min)  #these are series method

  first last email
0     C    S     .
1     J    D     .
2     J    S     .

In [50]:
people_df.applymap(len)

   first  last  email
0      5     7     22
1      4     3     17
2      4     5     17

In [58]:
people_df.applymap(str.upper)

   first     last                   email
0  COREY  SCHAFER  COREYSCHAFER@GMAIL.COM
1   JANE      DOE       JANEDOE@GMAIL.COM
2   JOHN    SMITH       JOHNDOE@GMAIL.COM

In [57]:
people_df

   first     last                   email
0  Corey  Schafer  coreyschafer@gmail.com
1   Jane      Doe       janedoe@gmail.com
2   John    Smith       johndoe@gmail.com

In [59]:
#map only works on a series
#it is used to substitue values with another values
people_df['first'].map({'Corey':'Chris','Jane':'Mary'})

#for the values that does not get passed in it returns NAN

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

In [60]:
people_df

   first     last                   email
0  Corey  Schafer  coreyschafer@gmail.com
1   Jane      Doe       janedoe@gmail.com
2   John    Smith       johndoe@gmail.com

In [61]:
people_df['first'].replace({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2     John
Name: first, dtype: object

In [62]:
people_df

   first     last                   email
0  Corey  Schafer  coreyschafer@gmail.com
1   Jane      Doe       janedoe@gmail.com
2   John    Smith       johndoe@gmail.com

In [67]:
schema_df = pd.read_csv('/content/survey_results_schema.csv')
df = pd.read_csv('/content/survey_results_public.csv')

In [68]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [70]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9943,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, back-end",9,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Yes,I am not interested in new job opportunities,Less than a year ago,Interview with people in peer roles;Interview ...,Yes,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",UAH,Ukrainian hryvnia,64000.0,Monthly,27696.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Lack of support f...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,I have some influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL,MongoDB;MySQL;Redis,MongoDB;MySQL;Redis,Docker;Linux,Docker;Linux,jQuery;Other(s):,React.js;Other(s):,NaN,Node.js,PHPStorm,Linux-based,"Development;Outside of work, for personal proj...",NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Difficult
9902,9944,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",4,20,4,Slightly dissatisfied,Neither satisfied nor dissatisfied,Somewhat confident,Not sure,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard)",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,INR,Indian rupee,NaN,Monthly,NaN,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work,"More than half, but not all, the time",Office,Far above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Not sure,I have little or no influence,Java;JavaScript;SQL,Java;JavaScript;Other(s):,MySQL,MongoDB;MySQL,AWS;Linux;Windows,AWS;Google Cloud Platform;Linux;Windows,jQuery,Express;jQuery;Spring,NaN,Ansible;Node.js,Eclipse;PyCharm;Visual Studio Code,Windows,I do not use containers,NaN,NaN,Yes,Yes,What?,Instagram,In real life (in person),Login,2013,Multiple times per day,Find answers to specific questions,3-5 times per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
9903,9945,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed part-time,United States,"Yes, full-time",Associate degree,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,"Developer, back-end;Developer, front-end;Devel...",6,14,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,NaN,NaN,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;C#;HTML/CSS;Java;JavaScript;SQL;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,Microsoft SQL Server;MySQL;SQLite,Microsoft SQL Server;MySQL;SQLite,NaN,NaN,Angular/Angular.js;ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET;.NET Core;Node.js,.NET Core;Node.js,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,NaN,No,Also Yes,No,Twitter,Online,Username,2014,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,21.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
9904,9946,I am a developer by profession,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",500 to 999 employees,"Developer, embedded applications or devices;De...",8,15,2,Slightly satisfied,Neither satisfied nor dissatisfied,Very confident,Not sure,Yes,I am actively looking for a job,1-2 years ago,Write any code;Interview with people in peer r...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,75000.0,Yearly,75000.0,35.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",2.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C;C#,C#;Rust;TypeScript,MySQL,DynamoDB;MongoDB;MySQL,Android;iOS,Android;Docker;iOS;Raspberry Pi;Slack,NaN,ASP.NET;React.js;Spring;Vue.js,.NET;.NET Core;Unity 3D;Xamarin,Flutter;.NET;.NET Core;React Native;Xamarin,Visual Studio;Visual Studio Code,Windows,NaN,Not at all,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Login,I don't remember,Daily or almost daily,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers,23.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
9905,9947,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...","1,000 to 4,999 employees","Developer, back-end;Developer, front-end;Devel...",22,9,10,Very satisfied,Very satisfied,Very confident,Yes,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,117000.0,Yearly,117000.0,45.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Java;JavaScript;Kotlin;SQL,C++;Erlang;Go;JavaScript;Kotlin,Microsoft SQL Server;SQLite,NaN,Android,Android;Arduino;AWS;Docker;Raspberry Pi,React.js,React.js,React Native,React Native,Android Studio;IntelliJ;Sublime Text;Vim,MacOS,I do not use containers,Not at all,An,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
#updating the name of the column
df.rename(columns = {'ConvertedComp': 'Salary[USD $]'}, inplace = True)

In [74]:
df['Salary[USD $]']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...
9901     27696.0
9902         NaN
9903         NaN
9904     75000.0
9905    117000.0
Name: Salary[USD $], Length: 9906, dtype: float64

In [75]:
df['Hobbyist']

0       Yes
1        No
2       Yes
3        No
4       Yes
       ...
9901    Yes
9902    Yes
9903    Yes
9904     No
9905    Yes
Name: Hobbyist, Length: 9906, dtype: object

In [76]:
# map is used to substitute values
#for each yes convert it to True and so on....

df['Hobbyist'].map({'Yes':True,'No':False})

0        True
1       False
2        True
3       False
4        True
        ...
9901     True
9902     True
9903     True
9904    False
9905     True
Name: Hobbyist, Length: 9906, dtype: bool

In [77]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes':True,'No':False})

In [78]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,Salary[USD $],WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,True,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",True,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9943,I am a developer by profession,True,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, back-end",9,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Yes,I am not interested in new job opportunities,Less than a year ago,Interview with people in peer roles;Interview ...,Yes,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",UAH,Ukrainian hryvnia,64000.0,Monthly,27696.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Lack of support f...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,I have some influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL,MongoDB;MySQL;Redis,MongoDB;MySQL;Redis,Docker;Linux,Docker;Linux,jQuery;Other(s):,React.js;Other(s):,NaN,Node.js,PHPStorm,Linux-based,"Development;Outside of work, for personal proj...",NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Difficult
9902,9944,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",4,20,4,Slightly dissatisfied,Neither satisfied nor dissatisfied,Somewhat confident,Not sure,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard)",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,INR,Indian rupee,NaN,Monthly,NaN,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work,"More than half, but not all, the time",Office,Far above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Not sure,I have little or no influence,Java;JavaScript;SQL,Java;JavaScript;Other(s):,MySQL,MongoDB;MySQL,AWS;Linux;Windows,AWS;Google Cloud Platform;Linux;Windows,jQuery,Express;jQuery;Spring,NaN,Ansible;Node.js,Eclipse;PyCharm;Visual Studio Code,Windows,I do not use containers,NaN,NaN,Yes,Yes,What?,Instagram,In real life (in person),Login,2013,Multiple times per day,Find answers to specific questions,3-5 times per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
9903,9945,I am a student who is learning to code,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed part-time,United States,"Yes, full-time",Associate degree,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,"Developer, back-end;Developer, front-end;Devel...",6,14,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,NaN,NaN,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;C#;HTML/CSS;Java;JavaScript;SQL;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,Microsoft SQL Server;MySQL;SQLite,Microsoft SQL Server;MySQL;SQLite,NaN,NaN,Angular/Angular.js;ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET;.NET Core;Node.js,.NET Core;Node.js,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,NaN,No,Also Yes,No,Twitter,Online,Username,2014,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,21.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
9904,9946,I am a developer by profession,False,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",500 to 999 employees,"Developer, embedded applications or devices;De...",8,15,2,Slightly satisfied,Neither satisfied nor dissatisfied,Very confident,Not sure,Yes,I am actively looking for a job,1-2 years ago,Write any code;Interview with people in peer r...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,75000.0,Yearly,75000.0,35.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",2.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C;C#,C#;Rust;TypeScript,MySQL,DynamoDB;MongoDB;MySQL,Android;iOS,Android;Docker;iOS;Raspberry Pi;Slack,NaN,ASP.NET;React.js;Spring;Vue.js,.NET;.NET Core;Unity 3D;Xamarin,Flutter;.NET;.NET Core;React Native;Xamarin,Visual Studio;Visual Studio Code,Windows,NaN,Not at all,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Login,I don't remember,Daily or almost daily,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers,23.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
9905,9947,I am a developer by profession,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...","1,000 to 4,999 employees","Developer, back-end;Developer, front-end;Devel...",22,9,10,Very satisfied,Very satisfied,Very confident,Yes,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,117000.0,Yearly,117000.0,45.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Java;JavaScript;Kotlin;SQL,C++;Erlang;Go;JavaScript;Kotlin,Microsoft SQL Server;SQLite,NaN,Android,Android;Arduino;AWS;Docker;Raspberry Pi,React.js,React.js,React Native,React Native,Android Studio;IntelliJ;Sublime Text;Vim,MacOS,I do not use containers,Not at all,An,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN